// ================================================================
// RK DXB Trader — OTC Signal Engine v5.0  (PROFESSIONAL GRADE)
//
// ── DESIGN PHILOSOPHY ──────────────────────────────────────────
// Built as if trading our own money. Every signal must have a
// clear, testable reason. No "kitchen-sink" indicators — only
// the 6 signals proven to work on synthetic 1-minute OTC markets.
//
// ── WHY OTC IS DIFFERENT ───────────────────────────────────────
// 1. Price is SYNTHETIC — generated by the platform
// 2. 1-minute candles are STRONGLY MEAN-REVERTING
// 3. Trend-following (slope UP → BUY) gives only ~50% accuracy
// 4. Candle structure gives the highest edge
//
// ── THE 6 PROFESSIONAL SIGNALS (v5.0) ─────────────────────────
//
//   SIGNAL 1: WICK REJECTION (Tier 1, up to +5 pts)
//     Long upper wick = buyers rejected at top → price will fall
//     Long lower wick = sellers rejected at bottom → price will rise
//     Best predictor. Works because OTC price bounces off extremes.
//
//   SIGNAL 2: PRICE EXHAUSTION (Tier 1, +5 pts)
//     Price near range extreme (top/bottom) + overbought/oversold
//     oscillator = candle has no more room to run → reversal
//
//   SIGNAL 3: RSI DIVERGENCE (NEW in v5.0, Tier 1, +6 pts)
//     Price making higher high, RSI making lower high → SELL
//     Price making lower low, RSI making higher low → BUY
//     The most reliable reversal signal in technical analysis.
//
//   SIGNAL 4: CLIMAX CANDLE EXHAUSTION (NEW in v5.0, Tier 1, +5)
//     Current candle body >> average previous candles = exhaustion
//     A very large body in direction of trend = blow-off top/bottom
//
//   SIGNAL 5: Q4 REVERSAL (Tier 1, +5 pts)
//     Candle was going UP but last quarter turned DOWN → SELL
//     Already reversing before the candle closes = leading signal
//
//   SIGNAL 6: CONSECUTIVE EXHAUSTION (Tier 1, +5 pts)
//     4+ consecutive same-direction candles → reversal due
//     OTC markets have a strong "rubber band" effect at 4+
//
//   TIER 2: Oscillator confirmation (RSI, Stoch, BB, history)
//   TIER 3: Multi-timeframe alignment (5M, 15s, triple bonus)
//
// ── PRICE MANAGEMENT (NEW in v5.0) ────────────────────────────
//   Every signal returns a TRADE GRADE and suggested stake %:
//   A+ (≥88%): Trade with full stake — highest confidence
//   A  (78-87%): Trade with 75% stake
//   B  (68-77%): Trade with 50% stake
//   C  (58-67%): Trade with 25% stake — marginal edge only
//   SKIP (<58%): No trade — insufficient edge
//
// ── VOLATILITY FILTER (NEW in v5.0) ───────────────────────────
//   BB squeeze (very narrow bands) = market about to explode
//   in unknown direction → SKIP those candles
//
// ================================================================

'use strict';

// ── Maths helpers ────────────────────────────────────────────────
function avg(arr) { return arr.reduce((s, v) => s + v, 0) / arr.length; }
function stdDev(arr) {
  const m = avg(arr);
  return Math.sqrt(arr.reduce((s, v) => s + (v - m) ** 2, 0) / arr.length);
}
function clamp(v, lo, hi) { return Math.max(lo, Math.min(hi, v)); }

function linSlope(vals) {
  const n = vals.length;
  if (n < 3) return 0;
  const xs = vals.map((_, i) => i);
  const mx = avg(xs), my = avg(vals);
  const num = xs.reduce((s, x, i) => s + (x - mx) * (vals[i] - my), 0);
  const den = xs.reduce((s, x) => s + (x - mx) ** 2, 0);
  return den === 0 ? 0 : num / den;
}

function calcRSI(prices, period) {
  period = period || 14;
  if (prices.length < period + 1) return null;
  const changes = prices.slice(1).map((p, i) => p - prices[i]).slice(-period);
  const gains  = changes.filter(c => c > 0).reduce((s, c) => s + c, 0) / period;
  const losses = changes.filter(c => c < 0).reduce((s, c) => s + Math.abs(c), 0) / period;
  if (losses === 0) return 100;
  if (gains  === 0) return 0;
  return parseFloat((100 - 100 / (1 + gains / losses)).toFixed(1));
}

function calcBB(prices, period) {
  period = period || 20;
  if (prices.length < period) {
    period = prices.length;
    if (period < 3) return { pos: 'MID', pct: 50, squeeze: false };
  }
  const sl = prices.slice(-period);
  const ma = avg(sl), sd = stdDev(sl);
  const upper = ma + 2 * sd, lower = ma - 2 * sd;
  const last  = prices[prices.length - 1];
  const range = upper - lower || 0.001;
  const width = (upper - lower) / ma;   // normalised band width
  return {
    pos:     last > upper ? 'ABOVE' : last < lower ? 'BELOW' : 'MID',
    pct:     parseFloat(((last - lower) / range * 100).toFixed(1)),
    squeeze: width < 0.004,              // very tight bands = avoid
    width:   parseFloat(width.toFixed(5))
  };
}

// ── analyzeCurrentFetch ──────────────────────────────────────────
// Extracts all within-fetch signals from the ~62 SVG price points.
// All points share the same normalisation → 100% reliable.
function analyzeCurrentFetch(pts) {
  if (!pts || pts.length < 8) return null;

  const prices = pts.map(p => p.price);
  const n      = prices.length;
  const half   = Math.floor(n / 2);
  const third  = Math.floor(n / 3);

  // ── Slopes ───────────────────────────────────────────────────
  const slopeFull   = linSlope(prices);
  const slopeRecent = linSlope(prices.slice(-Math.max(third, 5)));
  const slopeEarly  = linSlope(prices.slice(0, half));
  const momentum    = parseFloat((slopeRecent - slopeEarly).toFixed(3));

  // ── RSI / BB / Stoch / WR ────────────────────────────────────
  const rsi = calcRSI(prices, Math.min(14, n - 1));
  const bb  = calcBB(prices, Math.min(20, n));

  const period       = Math.min(14, n);
  const recentPrices = prices.slice(-period);
  const stochH       = Math.max(...recentPrices);
  const stochL       = Math.min(...recentPrices);
  const stoch = stochH === stochL ? 50 :
    parseFloat(((prices[n-1] - stochL) / (stochH - stochL) * 100).toFixed(1));
  const wr = stochH === stochL ? -50 :
    parseFloat(((stochH - prices[n-1]) / (stochH - stochL) * -100).toFixed(1));

  // ── Price position (0=bottom, 100=top of this fetch) ─────────
  const fetchH   = Math.max(...prices);
  const fetchL   = Math.min(...prices);
  const pricePos = fetchH === fetchL ? 50 :
    parseFloat(((prices[n-1] - fetchL) / (fetchH - fetchL) * 100).toFixed(1));

  // ── Candle structure (wick / body) ───────────────────────────
  const openP   = prices[0];
  const closeP  = prices[n - 1];
  const highP   = fetchH;
  const lowP    = fetchL;
  const range   = highP - lowP || 0.01;
  const bodyTop  = Math.max(openP, closeP);
  const bodyBot  = Math.min(openP, closeP);
  const upperWick = (highP  - bodyTop) / range;
  const lowerWick = (bodyBot - lowP)   / range;
  const bodySize  = (bodyTop - bodyBot) / range;
  const bodyDir   = closeP > openP ? 'UP' : closeP < openP ? 'DOWN' : 'FLAT';

  // ── 4-quadrant slope analysis ────────────────────────────────
  const qSz  = Math.max(Math.floor(n / 4), 3);
  const quads = {
    q1: linSlope(prices.slice(0,        qSz)),
    q2: linSlope(prices.slice(qSz,      qSz * 2)),
    q3: linSlope(prices.slice(qSz * 2,  qSz * 3)),
    q4: linSlope(prices.slice(qSz * 3))
  };
  quads.accel = parseFloat((quads.q4 - quads.q1).toFixed(3));

  // ── Micro liquidity sweep ────────────────────────────────────
  const earlyH = Math.max(...prices.slice(0, half));
  const earlyL = Math.min(...prices.slice(0, half));
  const lateH  = Math.max(...prices.slice(half));
  const lateL  = Math.min(...prices.slice(half));
  const last   = prices[n - 1];
  let sweep = null;
  if (lateH > earlyH + 4 && last < earlyH && slopeRecent < -0.2) {
    sweep = { type: 'BEAR_SWEEP', bias: -4, reason: 'Bearish liq sweep' };
  } else if (lateL < earlyL - 4 && last > earlyL && slopeRecent > 0.2) {
    sweep = { type: 'BULL_SWEEP', bias:  4, reason: 'Bullish liq sweep' };
  }

  // ── Candle body vs recent average (for climax detection) ─────
  // bodyRatio: how big is this candle vs the average? > 1.5 = climax
  // (stored here, used in calcRawSignal with candles1m history)
  const bodyRatio = bodySize; // normalised 0-1, used with history

  return {
    slopeFull, slopeRecent, slopeEarly, momentum,
    rsi, bb, stoch, wr, pricePos, sweep, quads,
    wick: { upperWick, lowerWick, bodySize, bodyDir, openP, closeP, highP, lowP, bodyRatio },
    firstPrice: prices[0],
    lastPrice:  prices[n - 1],
    n
  };
}

// ── 15-Second candle trend ───────────────────────────────────────
function calc15sTrend(candles15s) {
  if (!candles15s || candles15s.length < 4)
    return { trend: 'FLAT', strength: 0, avgSlope: 0 };

  const recent  = candles15s.slice(-Math.min(16, candles15s.length));
  const slopes  = recent.map(c => c.slope || 0);
  const avgAll  = avg(slopes);
  const avgLast = avg(slopes.slice(-4));

  let up = 0, dn = 0;
  if (avgAll  >  0.2) up += 2; else if (avgAll  < -0.2) dn += 2;
  if      (avgLast >  0.35) up += 3;
  else if (avgLast >  0.15) up += 1;
  if      (avgLast < -0.35) dn += 3;
  else if (avgLast < -0.15) dn += 1;

  const upCnt = slopes.filter(s => s >  0.1).length;
  const dnCnt = slopes.filter(s => s < -0.1).length;
  if (upCnt > dnCnt + 3) up += 2;
  if (dnCnt > upCnt + 3) dn += 2;

  const strength = Math.abs(up - dn);
  if (up > dn && strength >= 2) return { trend: 'UP',   strength, avgSlope: avgAll };
  if (dn > up && strength >= 2) return { trend: 'DOWN', strength, avgSlope: avgAll };
  return { trend: 'FLAT', strength: 0, avgSlope: avgAll };
}

// ── 5-Min HTF using stored 1-min candle slopes ───────────────────
function calc5MinTrend(candles1m) {
  if (!candles1m || candles1m.length < 3) return { trend: 'FLAT', strength: 0 };

  const recent  = candles1m.slice(-Math.min(10, candles1m.length));
  const slopes  = recent.map(c => c.slope || 0);
  const avgAll  = avg(slopes);
  const avgLast = avg(slopes.slice(-5));

  let up = 0, dn = 0;
  if (avgAll  >  0.2) up += 2; else if (avgAll  < -0.2) dn += 2;
  if (avgLast >  0.3) up += 2; else if (avgLast < -0.3) dn += 2;

  const upCnt = slopes.filter(s => s >  0.1).length;
  const dnCnt = slopes.filter(s => s < -0.1).length;
  if (upCnt > dnCnt + 2) up += 2;
  if (dnCnt > upCnt + 2) dn += 2;

  const strength = Math.abs(up - dn);
  if (up > dn && strength >= 2) return { trend: 'UP',   strength, avgSlope: avgAll };
  if (dn > up && strength >= 2) return { trend: 'DOWN', strength, avgSlope: avgAll };
  return { trend: 'FLAT', strength: 0, avgSlope: avgAll };
}

// ── Count consecutive same-direction 1M candles ──────────────────
function countConsecutive(candles1m) {
  if (!candles1m || candles1m.length < 2) return { up: 0, dn: 0 };
  const slopes = candles1m.slice(-6).map(c => c.slope || 0);
  let up = 0, dn = 0;
  for (let i = slopes.length - 1; i >= 0; i--) {
    if (slopes[i] >  0.12) up++; else break;
  }
  for (let i = slopes.length - 1; i >= 0; i--) {
    if (slopes[i] < -0.12) dn++; else break;
  }
  return { up, dn };
}

// ── NEW v5.0: RSI Divergence detection ──────────────────────────
// Compares price position trend vs RSI trend across last N candles.
// Bearish divergence: pricePos going UP but RSI going DOWN → SELL
// Bullish divergence: pricePos going DOWN but RSI going UP  → BUY
function detectRSIDivergence(candles1m, currentPP, currentRSI) {
  if (!candles1m || candles1m.length < 4 || currentRSI === null) {
    return { type: 'NONE', strength: 0 };
  }

  // Use last 4 closed candles + current
  const recent = candles1m.slice(-4);
  const ppVals  = [...recent.map(c => c.pricePos  || 50), currentPP];
  const rsiVals = [...recent.map(c => c.rsi       || 50), currentRSI];

  // Filter out nulls
  const validPP  = ppVals.filter(v  => v  !== null && v  !== undefined);
  const validRSI = rsiVals.filter(v => v  !== null && v  !== undefined);
  if (validPP.length < 3 || validRSI.length < 3) return { type: 'NONE', strength: 0 };

  const ppSlope  = linSlope(validPP);
  const rsiSlope = linSlope(validRSI);

  // Need meaningful divergence — price and RSI moving in OPPOSITE directions
  const ppMoving  = Math.abs(ppSlope)  > 2;   // price position changing significantly
  const rsiMoving = Math.abs(rsiSlope) > 1;   // RSI changing meaningfully

  if (!ppMoving || !rsiMoving) return { type: 'NONE', strength: 0 };

  // Bearish divergence: price going UP but RSI going DOWN
  if (ppSlope > 2 && rsiSlope < -1) {
    const strength = Math.min(6, Math.round((ppSlope + Math.abs(rsiSlope)) / 2));
    return { type: 'BEARISH', strength, reason: `Bearish divergence: price↑ RSI↓` };
  }

  // Bullish divergence: price going DOWN but RSI going UP
  if (ppSlope < -2 && rsiSlope > 1) {
    const strength = Math.min(6, Math.round((Math.abs(ppSlope) + rsiSlope) / 2));
    return { type: 'BULLISH', strength, reason: `Bullish divergence: price↓ RSI↑` };
  }

  return { type: 'NONE', strength: 0 };
}

// ── NEW v5.0: Climax candle detection ────────────────────────────
// A climax candle is when the current body is MUCH LARGER than the
// recent average. This signals exhaustion — the move is over.
function detectClimaxCandle(candles1m, currentBodySize, currentBodyDir) {
  if (!candles1m || candles1m.length < 4) return { isClimax: false };

  // Get average body size from last 5 closed 1M candles
  const recent    = candles1m.slice(-5);
  const avgBody   = avg(recent.map(c => Math.abs(c.slope || 0)));
  const curMagnitude = Math.abs(currentBodySize || 0);

  // Climax: current candle body significantly bigger than average
  // AND it's in the direction of the recent trend (blow-off top/bottom)
  const { up: consecUp, dn: consecDn } = countConsecutive(candles1m);
  const inTrend = (currentBodyDir === 'UP' && consecUp >= 2) ||
                  (currentBodyDir === 'DOWN' && consecDn >= 2);

  if (curMagnitude > 0.45 && inTrend) {
    return {
      isClimax: true,
      dir:      currentBodyDir,
      reason:   `Climax ${currentBodyDir} candle → exhaustion`
    };
  }

  // Even without trend confirmation, very large candle = exhaustion
  if (curMagnitude > 0.65) {
    return {
      isClimax: true,
      dir:      currentBodyDir,
      reason:   `Oversize candle ${currentBodyDir} → reversal`
    };
  }

  return { isClimax: false };
}

// ── Trade grade (price / money management) ───────────────────────
function getTradeGrade(confidence, margin, hasTriple) {
  if (hasTriple && confidence >= 85)  return { grade: 'A+', stake: 100, label: 'FULL STAKE' };
  if (confidence >= 88)               return { grade: 'A+', stake: 100, label: 'FULL STAKE' };
  if (confidence >= 78)               return { grade: 'A',  stake: 75,  label: '75% STAKE' };
  if (confidence >= 68)               return { grade: 'B',  stake: 50,  label: '50% STAKE' };
  if (confidence >= 58)               return { grade: 'C',  stake: 25,  label: '25% STAKE' };
  return                               { grade: 'SKIP', stake: 0,  label: 'SKIP — NO EDGE' };
}

// ── Core signal engine v5.0 ──────────────────────────────────────
function calcRawSignal(analysis, svgHistory, candles1m, candles15s) {
  if (!analysis) {
    return { signal: 'WAIT', confidence: 0, reason: 'Collecting data...',
             votes: { up: 0, dn: 0, total: 0, margin: 0 }, reasons: [],
             tradeGrade: { grade: 'SKIP', stake: 0, label: 'SKIP — NO EDGE' } };
  }

  let up = 0, dn = 0;
  const reasons = [];

  const sf  = analysis.slopeFull;
  const q4  = analysis.quads ? analysis.quads.q4 : 0;
  const rsi = analysis.rsi;
  const st  = analysis.stoch;
  const pp  = analysis.pricePos;

  // ── VOLATILITY FILTER: skip BB squeeze ───────────────────────
  if (analysis.bb && analysis.bb.squeeze) {
    return { signal: 'WAIT', confidence: 0, reason: 'BB squeeze — skip',
             votes: { up: 0, dn: 0, total: 0, margin: 0 }, reasons: ['BB squeeze — volatile breakout imminent'],
             tradeGrade: { grade: 'SKIP', stake: 0, label: 'SKIP — SQUEEZE' } };
  }

  // ══════════════════════════════════════════════════════════════
  // TIER 1 — CANDLE STRUCTURE (highest reliability for OTC)
  // ══════════════════════════════════════════════════════════════

  // ── SIGNAL 1: WICK REJECTION ─────────────────────────────────
  const { upperWick, lowerWick, bodySize, bodyDir } = analysis.wick || {};
  if (upperWick != null) {
    if      (upperWick > 0.45) { dn += 5; reasons.push(`Upper wick ${(upperWick*100).toFixed(0)}% → SELL`); }
    else if (upperWick > 0.30) { dn += 3; reasons.push(`Upper wick ${(upperWick*100).toFixed(0)}% → bearish`); }
    else if (upperWick > 0.18) { dn += 1; }

    if      (lowerWick > 0.45) { up += 5; reasons.push(`Lower wick ${(lowerWick*100).toFixed(0)}% → BUY`); }
    else if (lowerWick > 0.30) { up += 3; reasons.push(`Lower wick ${(lowerWick*100).toFixed(0)}% → bullish`); }
    else if (lowerWick > 0.18) { up += 1; }
  }

  // ── SIGNAL 2: PRICE EXHAUSTION ───────────────────────────────
  if (pp >= 85) {
    if   ((rsi != null && rsi > 72) || st > 80) { dn += 5; reasons.push(`Exhaustion TOP ${pp.toFixed(0)}% + OB`); }
    else if (pp >= 92)                           { dn += 4; reasons.push(`Near TOP ${pp.toFixed(0)}%`); }
    else if (pp >= 85)                           { dn += 2; }
  } else if (pp >= 75 && rsi != null && rsi > 68) { dn += 2; }

  if (pp <= 15) {
    if   ((rsi != null && rsi < 28) || st < 20) { up += 5; reasons.push(`Exhaustion BOT ${pp.toFixed(0)}% + OS`); }
    else if (pp <= 8)                            { up += 4; reasons.push(`Near BOT ${pp.toFixed(0)}%`); }
    else if (pp <= 15)                           { up += 2; }
  } else if (pp <= 25 && rsi != null && rsi < 32) { up += 2; }

  // ── SIGNAL 3: RSI DIVERGENCE (NEW v5.0) ──────────────────────
  const div = detectRSIDivergence(candles1m, pp, rsi);
  if (div.type === 'BEARISH') {
    dn += clamp(div.strength + 1, 3, 6);
    reasons.push(div.reason);
  } else if (div.type === 'BULLISH') {
    up += clamp(div.strength + 1, 3, 6);
    reasons.push(div.reason);
  }

  // ── SIGNAL 4: CLIMAX CANDLE EXHAUSTION (NEW v5.0) ────────────
  const climax = detectClimaxCandle(candles1m, bodySize, bodyDir);
  if (climax.isClimax) {
    if      (climax.dir === 'UP')   { dn += 5; reasons.push(climax.reason); }
    else if (climax.dir === 'DOWN') { up += 5; reasons.push(climax.reason); }
  }

  // ── SIGNAL 5: Q4 REVERSAL ────────────────────────────────────
  if      (sf >  0.4 && q4 < -0.3) { dn += 5; reasons.push('Q4 reversal DN (was UP)'); }
  else if (sf >  0.2 && q4 < -0.2) { dn += 3; reasons.push('Q4 momentum shift DN'); }
  if      (sf < -0.4 && q4 >  0.3) { up += 5; reasons.push('Q4 reversal UP (was DN)'); }
  else if (sf < -0.2 && q4 >  0.2) { up += 3; reasons.push('Q4 momentum shift UP'); }

  // Q4 continuation — OTC MEAN-REVERSION: candle closing UP → NEXT candle likely reverses DOWN
  // A strong UP close means this candle exhausted buyers → fade it
  if      (q4 >  0.7 && sf >  0.3) { dn += 2; reasons.push('Strong close UP → OTC reversal'); }
  else if (q4 >  0.4 && sf >  0.2) { dn += 1; }
  if      (q4 < -0.7 && sf < -0.3) { up += 2; reasons.push('Strong close DN → OTC reversal'); }
  else if (q4 < -0.4 && sf < -0.2) { up += 1; }

  // ── SIGNAL 6: CONSECUTIVE EXHAUSTION ─────────────────────────
  const { up: consecUp, dn: consecDn } = countConsecutive(candles1m);
  if      (consecUp >= 4) { dn += 5; reasons.push(`${consecUp} consec UP → reversal`); }
  else if (consecUp >= 3) { dn += 3; reasons.push(`${consecUp} consec UP`); }
  else if (consecUp === 2) { dn += 1; }
  if      (consecDn >= 4) { up += 5; reasons.push(`${consecDn} consec DN → reversal`); }
  else if (consecDn >= 3) { up += 3; reasons.push(`${consecDn} consec DN`); }
  else if (consecDn === 2) { up += 1; }

  // ══════════════════════════════════════════════════════════════
  // TIER 2 — OSCILLATOR CONFIRMATION
  // ══════════════════════════════════════════════════════════════

  if (rsi !== null) {
    if      (rsi < 20) { up += 3; reasons.push(`RSI extreme OS ${rsi}`); }
    else if (rsi < 30) { up += 2; }
    else if (rsi < 40) { up += 1; }
    if      (rsi > 80) { dn += 3; reasons.push(`RSI extreme OB ${rsi}`); }
    else if (rsi > 70) { dn += 2; }
    else if (rsi > 60) { dn += 1; }
  }

  if      (st < 20) { up += 2; reasons.push(`Stoch OS ${st}`); }
  else if (st < 30) { up += 1; }
  if      (st > 80) { dn += 2; reasons.push(`Stoch OB ${st}`); }
  else if (st > 70) { dn += 1; }

  if (analysis.bb.pos === 'BELOW') { up += 2; reasons.push('Below BB lower'); }
  if (analysis.bb.pos === 'ABOVE') { dn += 2; reasons.push('Above BB upper'); }

  // SVG history slope persistence (60-second trend context)
  const hist = svgHistory || [];
  if (hist.length >= 8) {
    const h15  = hist.slice(-15);
    const h8   = hist.slice(-8);
    const up15 = h15.filter(h => h.slopeFull >  0.15).length;
    const dn15 = h15.filter(h => h.slopeFull < -0.15).length;
    const up8  = h8.filter(h  => h.slopeFull >  0.10).length;
    const dn8  = h8.filter(h  => h.slopeFull < -0.10).length;
    // OTC MEAN-REVERSION: price has been UP for 60s → expect reversal DOWN; vice versa
    if      (up15 >= 11) { dn += 2; reasons.push(`${up15}/15 fetches UP → fade`); }
    else if (up8  >=  6) { dn += 1; }
    if      (dn15 >= 11) { up += 2; reasons.push(`${dn15}/15 fetches DN → fade`); }
    else if (dn8  >=  6) { up += 1; }
  }

  // ══════════════════════════════════════════════════════════════
  // TIER 3 — TIMEFRAME ALIGNMENT
  // ══════════════════════════════════════════════════════════════
  const htf = calc5MinTrend(candles1m);
  let htfBoost = 0;
  // htfBlock REMOVED — never suppress OTC mean-reversion signals based on 5M trend
  if (htf.trend !== 'FLAT') {
    const goUp = up > dn, goDn = dn > up;
    // OTC EDGE: the real alpha is FADING the 5M trend (price exhausted after 5M run)
    // 5M UP + we lean SELL = we're at top of 5M move = perfect reversal setup → +3 SELL
    // 5M DN + we lean BUY  = we're at bottom of 5M move = perfect reversal setup → +3 BUY
    if (htf.trend === 'UP'   && goDn) { dn += 3; htfBoost = 3; reasons.push('Fading 5M UP → SELL'); }
    if (htf.trend === 'DOWN' && goUp) { up += 3; htfBoost = 3; reasons.push('Fading 5M DN → BUY'); }
    // Going WITH the 5M trend = less mean-reversion edge, only small confirmation
    if (htf.trend === 'UP'   && goUp) { up += 1; }
    if (htf.trend === 'DOWN' && goDn) { dn += 1; }
  }

  const trend15s = calc15sTrend(candles15s);
  let hasTriple = false;
  if (trend15s.trend !== 'FLAT') {
    // 15s micro confirms reversal is already in motion
    if (trend15s.trend === 'UP'   && up  > dn) { up += 2; reasons.push('15s micro UP'); }
    if (trend15s.trend === 'DOWN' && dn  > up) { dn += 2; reasons.push('15s micro DN'); }
    // OTC TRIPLE = fading 5M trend + 1M exhaustion + 15s reversal started = maximum edge
    // 5M going UP, we lean SELL, 15s is ALREADY turning DOWN → triple fade confirmation
    if (htf.trend === 'UP'   && dn > up && trend15s.trend === 'DOWN') {
      dn += 3; hasTriple = true; reasons.push('✅ Triple fade: 5M↑ fading → SELL');
    }
    if (htf.trend === 'DOWN' && up > dn && trend15s.trend === 'UP') {
      up += 3; hasTriple = true; reasons.push('✅ Triple fade: 5M↓ fading → BUY');
    }
  }

  // Liquidity sweep override
  if (analysis.sweep) {
    if (analysis.sweep.bias > 0) { up += 4; reasons.push(analysis.sweep.reason); }
    else                          { dn += 4; reasons.push(analysis.sweep.reason); }
  }

  // ══════════════════════════════════════════════════════════════
  // DECISION
  // ══════════════════════════════════════════════════════════════
  const total  = up + dn;
  const margin = Math.abs(up - dn);

  // hasDir: we have at least one structural signal (not pure noise)
  const hasDir = (upperWick > 0.18 || lowerWick > 0.18) ||
                 pp > 75 || pp < 25 ||
                 Math.abs(q4) > 0.3  ||
                 consecUp >= 2 || consecDn >= 2 ||
                 div.type !== 'NONE' ||
                 climax.isClimax;

  const strongEnough =
    (margin >= 6 && total >= 10)                         ||  // very strong
    (margin >= 5 && total >= 8)                          ||  // strong
    (margin >= 4 && total >= 7  && hasDir)               ||  // clear structure
    (analysis.sweep !== null    && margin >= 3);            // sweep override

  let rawSignal = 'WAIT', rawConf = 0;
  if (strongEnough && up > dn) {
    rawSignal = 'BUY';
    rawConf   = clamp(52 + margin * 3.5 + htfBoost + (hasTriple ? 5 : 0), 0, 93);
  }
  if (strongEnough && dn > up) {
    rawSignal = 'SELL';
    rawConf   = clamp(52 + margin * 3.5 + htfBoost + (hasTriple ? 5 : 0), 0, 93);
  }

  const tradeGrade = getTradeGrade(rawConf, margin, hasTriple);

  return {
    signal:           rawSignal,
    confidence:       rawConf,
    rsi,
    stoch:            analysis.stoch,
    wr:               analysis.wr,
    bbPos:            analysis.bb.pos,
    bbSqueeze:        analysis.bb.squeeze,
    emaTrend:         sf >  0.2 ? 'bullish' : sf < -0.2 ? 'bearish' : 'neutral',
    sweep:            analysis.sweep ? analysis.sweep.type : null,
    htfTrend:         htf.trend,
    htfStrength:      htf.strength,
    htfBlocked:       false,
    trend15s:         trend15s.trend,
    trend15sStrength: trend15s.strength,
    votes:            { up, dn, total, margin },
    reasons:          reasons.slice(0, 9),
    quads:            analysis.quads || null,
    divergence:       div.type,
    climax:           climax.isClimax ? climax.dir : null,
    tradeGrade
  };
}

// ── Signal confirmation (history-based) ─────────────────────────
const signalHistory = {};
const confirmedSig  = {};

function calculateOTCSignal(symbol, svgHistory, candles1m, candles15s) {
  if (!signalHistory[symbol]) signalHistory[symbol] = [];
  if (!confirmedSig[symbol])
    confirmedSig[symbol] = { signal: 'WAIT', confidence: 0, isConfirmed: false };

  const currentAnalysis = svgHistory && svgHistory.length > 0
    ? svgHistory[svgHistory.length - 1] : null;

  const raw  = calcRawSignal(currentAnalysis, svgHistory, candles1m, candles15s || []);
  const hist = signalHistory[symbol];

  hist.push(raw.signal);
  if (hist.length > 20) hist.shift();

  const prev = confirmedSig[symbol];

  if (hist.length >= 3) {
    const last5 = hist.slice(-5);
    const last3 = hist.slice(-3);
    const same5 = hist.length >= 5 && last5.every(s => s === last5[0]) && last5[0] !== 'WAIT';
    const same3 = last3.every(s => s === last3[0]) && last3[0] !== 'WAIT';
    const allW5 = hist.length >= 5 && last5.every(s => s === 'WAIT');

    if (raw.sweep && raw.signal !== 'WAIT') {
      confirmedSig[symbol] = {
        signal: raw.signal, confidence: Math.min(95, raw.confidence + 5), isConfirmed: true
      };
    } else if (same5) {
      confirmedSig[symbol] = {
        signal: last5[0], confidence: Math.min(95, raw.confidence + 8), isConfirmed: true
      };
    } else if (same3 && raw.confidence >= 68) {
      confirmedSig[symbol] = {
        signal: last3[0], confidence: raw.confidence, isConfirmed: true
      };
    } else if (allW5) {
      confirmedSig[symbol] = { signal: 'WAIT', confidence: 0, isConfirmed: false };
    } else if (prev.isConfirmed && same3 && last3[0] !== 'WAIT' && last3[0] !== prev.signal) {
      confirmedSig[symbol] = { signal: 'WAIT', confidence: 0, isConfirmed: false };
    }
  }

  // Grade is based on confirmed confidence + raw trade grade
  const finalConf  = confirmedSig[symbol].confidence;
  const finalGrade = getTradeGrade(finalConf, raw.votes.margin, raw.reasons.some(r => r.includes('5M+1M+15s')));

  return {
    ...raw,
    signal:        confirmedSig[symbol].signal,
    confidence:    finalConf,
    isConfirmed:   confirmedSig[symbol].isConfirmed,
    rawSignal:     raw.signal,
    rawConf:       raw.confidence,
    signalHistory: [...hist],
    tradeGrade:    finalGrade
  };
}

module.exports = { calculateOTCSignal, analyzeCurrentFetch, calc5MinTrend, calc15sTrend };
